# This version of config.mak was generated by:
# ./configure
# Any changes made here will be lost if configure is re-run
AR = $(CROSS_COMPILE)ar
RANLIB = $(CROSS_COMPILE)ranlib
CC = clang
ARCH = wasm32
CROSS_COMPILE = llvm-
