# This version of config.mak was generated by:
# ./configure
# Any changes made here will be lost if configure is re-run
COMPILER_BIN = ../llvm-project/build/bin
AR = $(COMPILER_BIN)/$(CROSS_COMPILE)ar
RANLIB = $(COMPILER_BIN)/$(CROSS_COMPILE)ranlib
CC = $(COMPILER_BIN)/clang
ARCH = wasm32
CROSS_COMPILE = llvm-
